#GET TASKS
http://localhost:3000/tasks

###

#GET TASK BY ID
http://localhost:3000/tasks/627447acd07a3d9eee0e9c31

###

#POST TASK
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "testing yet more MODULARITY",
    "notes": ":(((",
    "start_time": "2023-06-25T12:00:00.000Z",
    "end_time": "2023-07-28T12:30:00.000Z",
    "hour_estimate": "3000",
    "completed": false
}

###

#UPDATE TASK BY ID
PUT http://localhost:3000/tasks/627447acd07a3d9eee0e9c31
content-type: application/json

{
    "title": "testing API"
}

###

#DELETE TASK BY ID
DELETE http://localhost:3000/tasks/6271b4d201b5d583671dc51c
